### ISSUE TITLE
Website is not working

### ISSUE THREAD

**Issue by galaxy2211** [Notavone/discord-panel#6] opened 2020-06-11 11:25 UTC
It's working yesterday but not working today

**Comment by Notavone** [comment] 2020-06-19 23:01
did you change something in the code ? if not try re-downloading the project

**Comment by galaxy2211** [comment] 2020-06-20 00:17
No after that day i can access thank-you

**Comment by Notavone** [comment] 2020-06-20 00:26
No problem, sorry for the inconvenience i'm not really active at the moment, if the problem is sovled i'm closing this issue

**Closed by Notavone** 2020-06-20 00:26 UTC
